# Generated by Django 4.2.11 on 2024-04-17 20:16

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_description', models.CharField(max_length=255)),
                ('num_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket_image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('id_ticket', models.ForeignKey(null=True, on_delete=tickets.models.ticket, to='tickets.ticket')),
            ],
        ),
    ]
