# Generated by Django 4.2.11 on 2024-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket_image',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
